version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: eslint-plugin-jsdoc
    versions:
    - 31.5.0
    - 31.6.0
    - 31.6.1
    - 32.0.0
    - 32.0.2
    - 32.0.3
    - 32.1.1
    - 32.3.1
    - 32.3.2
    - 32.3.3
  - dependency-name: eslint
    versions:
    - 7.24.0
  - dependency-name: "@commitlint/cli"
    versions:
    - 12.1.0
  - dependency-name: "@commitlint/config-conventional"
    versions:
    - 12.1.0
  - dependency-name: husky
    versions:
    - 5.1.0
    - 5.1.2
  - dependency-name: nock
    versions:
    - 13.0.8
  - dependency-name: semantic-release
    versions:
    - 17.3.8
